image: golang:1.19-buster

stages:
  - build
  - test
  - deploy

services:
  - docker:20.10.19-dind

# build the ifsc binary
build_ifsc:
  stage: build
  script:
    - sh build.sh
    - cp openapi.yaml public/
  artifacts:
    paths:
      - public
  only:
    changes:
      - Dockerfile
      - cmd/**/*.go
      - ./*.{sh,go,yml}

# download swagger ui & mv to public dir
swagger:
  image: busybox:latest
  variables:
    swagger_version: 5.9.1
  stage: build
  script:
    - if test -d public/; then \
      echo "Directory exists" \
      else \
      mkdir public/; fi
    - wget https://github.com/swagger-api/swagger-ui/archive/refs/tags/v$swagger_version.tar.gz
    - tar -xf v$swagger_version.tar.gz
    - mv swagger-ui-$swagger_version/dist public/
    - mv swagger-initializer.js public/

# check whether all cli commands are working
cli_api_tests:
  stage: test
  needs: ["build_ifsc"]
  script:
    - apt update && apt install -y curl
    - cd public/linux
    - chmod +x ifsc
    - ./ifsc index
    - ./ifsc check KARB0000001
    - ./ifsc search axis karol
    # REST API tests
    - ./ifsc server &
    - curl -f http://localhost:9000/HDFC0CAGSBK
    - curl -f http://localhost:9000/search?q=hitech%20city
  only:
    changes:
      - Dockerfile
      - cmd/**/*.go
      - ./*.{sh,go,yml}

# build the docker image & push to the dockerhub
docker_image:
  image: docker:20.10.19
  stage: deploy
  script:
    - docker login -u kskarthik -p $DOCKERHUB_TOKEN
    - docker build -t kskarthik/ifsc:$CI_COMMIT_TAG --build-arg IFSC_VERSION=$IFSC_VERSION .
    - docker tag kskarthik/ifsc:$CI_COMMIT_TAG kskarthik/ifsc:latest
    - docker push kskarthik/ifsc:latest
    - docker push kskarthik/ifsc:$CI_COMMIT_TAG
  only:
    - tags

# deploy the build_ifsc job artifcats gitlab pages when there is a release
pages:
  stage: deploy
  script:
    - ls public/
  artifacts:
    paths:
      - public
  # only:
  #   - tags
