image: golang:1.19-buster

stages:
  - build
  - deploy

services:
  - docker:20.10.19-dind

# build the ifsc binary
ifsc:
  stage: build
  script:
    - sh build.sh
  artifacts:
    paths:
      - public
  only:
    changes:
      - Dockerfile
      - cmd/**/*.go
      - ./*.{sh,go}

# build the docker image & push to the dockerhub
docker:
  image: docker:20.10.19
  stage: deploy
  script:
    - docker login -u kskarthik -p $DOCKERHUB_TOKEN
    - docker build -t kskarthik/ifsc:$CI_COMMIT_TAG --build-arg IFSC_VERSION=$IFSC_VERSION .
    - docker tag kskarthik/ifsc:$CI_COMMIT_TAG kskarthik/ifsc:latest
    - docker push kskarthik/ifsc:latest
    - docker push kskarthik/ifsc:$CI_COMMIT_TAG
  only:
    - tags

# deploy to gitlab pages
pages:
  stage: deploy
  script:
    - ls public/
  artifacts:
    paths:
      - public
  only:
    - tags
