image: golang:1.19-buster

stages:
  - build
  - deploy

services:
  - docker:20.10.19-dind

# build the ifsc binary
ifsc:
  stage: build
  script:
    - sh build.sh
  artifacts:
    paths:
      - public
  # rules:
  #   - if: $CI_COMMIT_REF_NAME == "master"
  changes:
    - Dockerfile
    - cmd/**/*.go
    - ./*.{sh,go}

# build the docker image & push to the dockerhub
docker:
  image: docker:20.10.19
  stage: build
  script:
    - docker login -u kskarthik -p $DOCKERHUB_TOKEN
    - docker build -t kskarthik/ifsc:latest --build-arg IFSC_VERSION=$IFSC_VERSION .
    - docker push kskarthik/ifsc:latest
  changes:
    - Dockerfile
    - cmd/**/*.go
    - ./*.{sh,go}

# deploy to gitlab pages
pages:
  stage: deploy
  script:
    - ls public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_REF_NAME == "master"
