image: golang:1.19-buster

pages:
  script:
    - wget https://github.com/razorpay/ifsc/releases/download/v2.0.12/IFSC.csv -P cmd/
    - sh build.sh
  artifacts:
    paths:
      - public
  only:
    refs:
      - branches
    changes:
      - Dockerfile
      - cmd/**/*.go
      - ./*.{sh,go}
