image: golang:1.19-buster

stages:
  - build
  - test
  - deploy

services:
  - docker:20.10.19-dind

# build the ifsc binary
ifsc:
  stage: build
  script:
    - sh build.sh
    - cp openapi.yaml public/
  artifacts:
    paths:
      - public
  only:
    changes:
      - Dockerfile
      - cmd/**/*.go
      - ./*.{sh,go,yml}

# check whether all cli commands are working
cli_api_tests:
  stage: test
  script:
    - apt update && apt install -y curl
    - cd public/linux
    - chmod +x ifsc
    - ./ifsc index
    - ./ifsc check KARB0000001
    - ./ifsc search axis karol
    # test server
    - ./ifsc server &
    - curl -f http://localhost:9000/HDFC0CAGSBK
    - curl -f http://localhost:9000/search?q=hitech%20city

# build the docker image & push to the dockerhub
docker:
  image: docker:20.10.19
  stage: deploy
  script:
    - docker login -u kskarthik -p $DOCKERHUB_TOKEN
    - docker build -t kskarthik/ifsc:$CI_COMMIT_TAG --build-arg IFSC_VERSION=$IFSC_VERSION .
    - docker tag kskarthik/ifsc:$CI_COMMIT_TAG kskarthik/ifsc:latest
    - docker push kskarthik/ifsc:latest
    - docker push kskarthik/ifsc:$CI_COMMIT_TAG
  only:
    - tags

# deploy to gitlab pages
pages:
  stage: deploy
  script:
    - ls public/
  artifacts:
    paths:
      - public
  only:
    - tags
