openapi: 3.0.3

info:
  title: go-ifsc
  description: API documentation for go-ifsc. A CLI / REST API server for searching details about Indian banks
  license:
    name: AGPLv3
    url: https://www.gnu.org/licenses/agpl-3.0.en.html

externalDocs:
  description: Find out more about go-ifsc
  url: https://gitlab.com/kskarthik/go-ifsc

servers:
  - url: https://ifsc.kskarthik.insomnia247.nl

components:
  schemas:
    ifsc-object:
      type: object
      properties:
        BANK:
          type: string
        IFSC:
          type: string
        BRANCH:
          type: string
        CENTER:
          type: string
        DISTRICT:
          type: string
        STATE:
          type: string
        ADDRESS:
          type: string
        CONTACT:
          type: string
        IMPS:
          type: boolean
        RTGS:
          type: boolean
        CITY:
          type: string
        ISO3166:
          type: string
        NEFT:
          type: boolean
        MICR:
          type: string
        UPI:
          type: boolean
        SWIFT:
          type: string
          nullable: true
paths:
  /:
    get:
      summary: Application Status
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  version:
                    type: string

  /{ifsc}:
    get:
      summary: validate an IFSC code
      parameters:
        - name: ifsc
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ifsc-object"
        "404":
          description: IFSC Code not found
  /search:
    get:
      summary: Search for banks
      description: the search query can be name, branch, address etc...
      parameters:
        - name: q
          in: query
          required: true
          schema:
            type: string
        - name: match
          in: query
          description: text matching pattern
          schema:
            enum: ["all", "any", "fuzzy", "adv"]
            default: any
        - name: limit
          description: search results limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ifsc-object"
        "400":
          description: Incorrect query parameters
  /fields:
    get:
      summary: Returns fields of a bank
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
